#include <bits/stdc++.h>
using namespace std;

void generateGraph(int n, int m, vector<int> adj[]){
    vector<pair<int, int>> edges = {
        {0, 1},
        {1, 2},
        {2, 3},
        {1, 3},
        {3, 4},
        {2, 4},
        {4, 5}
    };
    for (const auto& edge : edges) {
        int u = edge.first;
        int v = edge.second;
        adj[u].push_back(v);
        adj[v].push_back(u);
    }
}

// if ans generated by topo sort == no. of node in graph then there is no cycle

bool detectCycle(int v, vector<int> adj[]){
    int indegree[v] = {0};

    for(int i = 0; i < v; i++){
        for(auto it : adj[i]){
            indegree[it]++;
        }
    } 

    queue<int> q;
    for(int i = 0; i < v; i++){
        if(indegree[i] == 0) q.push(i);
    }

    vector<int> ans;

    while(!q.empty()){
        int node = q.front();
        q.pop();
        ans.push_back(node);

        for(auto adjacentNode : adj[node]){
            indegree[adjacentNode]--;
            if(indegree[adjacentNode] == 0){
                q.push(adjacentNode);
            }
        }
    }

    if(ans.size() == v) return false;
    return true;
}

int main(){
    int n = 6;
    int m = 6;
    vector<int> adj[n + 1];
    generateGraph(n, m , adj);
    
    cout << detectCycle(n, adj) << endl;
    return 0;
}